### PR TITLE
Add monolog 3

### PR DESCRIPTION
**Pull request by Seb33300**

### CODE REVIEW

**Comment by Seb33300** [comment]
@zaak can you please check this?

This bundle cannot be installed on a project using Monolog 3

**Comment by zaak** [comment]
Thank you for the PR @Seb33300! This PR needs to wait for now, because the Monolog version must also be updated in the CKFinder distribution package. Without this update, the PR won't work as intended.

**Review by zaak — APPROVED** [review]

**Comment by zaak** [comment]
The connector version will be updated soon, so let's merge this. Thank you @Seb33300!

**Comment by Seb33300** [comment]
Hi @zaak, you already updated the connector to 3.7.0 and if I am not wrong this version supports Monolog 3
Can you please [tag a new release](https://github.com/ckfinder/ckfinder-symfony-bundle/releases)?

**Comment by zaak** [comment]
Hi @Seb3330. [`v4.0.2`](https://packagist.org/packages/ckfinder/ckfinder-symfony-bundle#4.0.2) has been released a few days ago.

**Comment by Seb33300** [comment]
Oh right thanks.
Weird it's not showing as the latest:

image

**Pull request merged**
